ALTER TABLE "package_plans"
ADD COLUMN IF NOT EXISTS "swap_size" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "instances"
ADD COLUMN IF NOT EXISTS "swap_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "swap_size" INTEGER;
